# Generated by Django 4.2.3 on 2023-07-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kaynak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaynak_no', models.IntegerField()),
                ('kaynak_yontemi', models.CharField(max_length=50)),
                ('kaynakci_adi', models.CharField(max_length=50)),
                ('wps_no', models.IntegerField()),
                ('ndt_yontem', models.CharField(max_length=50)),
                ('ndt_sonucu', models.CharField(max_length=50)),
            ],
        ),
    ]
